### ISSUE TITLE
As a learner I would like to see a progress bar as I set up my profile

### ISSUE THREAD

**Issue by PJSalter** [fac24/alis-learning#19]

**Comment by joe-dev-public** [comment]
Mostly done, but still needs these changes:

- [ ] Don't use list items for arrows.
- [ ] Adjust styles so layout doesn't break on narrow viewports.
- [ ] Add key prop (React), I think a quick first attempt it still broken.
- [ ] Maybe: fix display of avatar and finish line :)
- [ ] Stretch: add green ticks/check marks to "completed" sections.

**Comment by joe-dev-public** [comment]
Rough work log:

- Tue end of day
- Wed most of day?
- Thu briefly ...
