### ISSUE TITLE
As a learner, I want to select the game

### ISSUE THREAD

**Issue by PJSalter** [fac24/alis-learning#28]

**Comment by joe-dev-public** [comment]
The MVP will quite possibly only have one game (phonemes).

Even if there's more than one game, I think the "game picker" screen is optional.

The alternative: the app automatically directs learners to a game, e.g. a random game, whatever game they didn't play last, the game where they've made least progress, etc.

(When we've built the progress map, clicking a "milestone" (lockable circle) would lead the user to either the game picker screen, or directly into a game. Prior to building the progress map, the final stage of onboarding would lead to the same place.)
